name = "history-arg-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

[observability]
enabled = true

[[vectorize]]
binding = "VECTORIZE"
index_name = "argentina-dictadura-docs"

[[d1_databases]]
binding = "DB"
database_name = "history-arg"
database_id = "24bb860f-58fc-49dc-8cc8-7bd90f31946c"

[ai]
binding = "AI"
