name = "history-arg-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

[observability]
enabled = true

[[vectorize]]
binding = "VECTORIZE"
index_name = "argentina-dictadura-docs"

[[d1_databases]]
binding = "DB"
database_name = "history-arg"
database_id = "" # Completar después de crear la DB con wrangler d1 create

[ai]
binding = "AI"
